# -*- encoding: utf-8 -*-
# kb v0.1.4
# A knowledge base organizer
# Copyright © 2020, gnc.
# See /LICENSE for licensing information.

#
# kbAPI server DOCKER compose file
# 
# :Copyright: © 2020, alshapton.
# :License: GPLv3 (see /LICENSE).
# 

version: '3.7'

services:
  kb:
    build:
      context: ./
      dockerfile: ./docker/api/dockerfile
    volumes:
      - ./docker/data:/data
    tty: true
    ports: 
      - 5000:5000
